import type { SourceConfig } from '../types'

// ======================================================
// AI Radar - 全部信源配置 (~130 sources)
// ======================================================

export const SOURCE_CONFIGS: SourceConfig[] = [
  // ── Official (9) ──
  {
    slug: 'openai-blog',
    name: 'OpenAI Blog',
    type: 'rss',
    category: 'official',
    url: 'https://openai.com/blog/rss.xml',
    home_url: 'https://openai.com/blog',
    priority: 10,
  },
  {
    slug: 'anthropic-blog',
    name: 'Anthropic Blog',
    type: 'rss',
    category: 'official',
    url: 'https://www.anthropic.com/rss.xml',
    home_url: 'https://www.anthropic.com/news',
    priority: 10,
  },
  {
    slug: 'deepmind-blog',
    name: 'Google DeepMind Blog',
    type: 'rss',
    category: 'official',
    url: 'https://deepmind.google/blog/rss.xml',
    home_url: 'https://deepmind.google/blog',
    priority: 9,
  },
  {
    slug: 'google-ai-blog',
    name: 'Google AI Blog',
    type: 'rss',
    category: 'official',
    url: 'https://blog.google/technology/ai/rss/',
    home_url: 'https://blog.google/technology/ai',
    priority: 9,
  },
  {
    slug: 'meta-ai-blog',
    name: 'Meta AI Blog',
    type: 'rss',
    category: 'official',
    url: 'https://ai.meta.com/blog/rss/',
    home_url: 'https://ai.meta.com/blog',
    priority: 9,
  },
  {
    slug: 'nvidia-ai-blog',
    name: 'NVIDIA AI Blog',
    type: 'rss',
    category: 'official',
    url: 'https://blogs.nvidia.com/feed/',
    home_url: 'https://blogs.nvidia.com/blog/category/generative-ai',
    priority: 8,
  },
  {
    slug: 'huggingface-blog',
    name: 'Hugging Face Blog',
    type: 'rss',
    category: 'official',
    url: 'https://huggingface.co/blog/feed.xml',
    home_url: 'https://huggingface.co/blog',
    priority: 9,
  },
  {
    slug: 'xai-blog',
    name: 'xAI Blog',
    type: 'rss',
    category: 'official',
    url: 'https://x.ai/blog/rss.xml',
    home_url: 'https://x.ai/blog',
    priority: 9,
  },
  {
    slug: 'google-gemini-blog',
    name: 'Google Gemini Blog',
    type: 'rss',
    category: 'official',
    url: 'https://blog.google/products/gemini/rss/',
    home_url: 'https://blog.google/products/gemini',
    priority: 9,
  },
  {
    slug: 'azure-ai-blog',
    name: 'Azure AI Blog',
    type: 'rss',
    category: 'official',
    url: 'https://azure.microsoft.com/en-us/blog/tag/ai/feed/',
    home_url: 'https://azure.microsoft.com/en-us/blog/tag/ai',
    priority: 8,
  },

  // ── 国内媒体 (2) ──
  {
    slug: '36kr',
    name: '36氪',
    type: 'rss',
    category: 'media',
    url: 'https://36kr.com/feed',
    home_url: 'https://36kr.com',
    priority: 7,
  },
  {
    slug: 'qbitai',
    name: '量子位',
    type: 'rss',
    category: 'media',
    url: 'https://www.qbitai.com/feed',
    home_url: 'https://www.qbitai.com',
    priority: 7,
  },

  // ── Community (4) ──
  {
    slug: 'hackernews',
    name: 'Hacker News',
    type: 'api',
    category: 'community',
    url: 'https://hacker-news.firebaseio.com/v0',
    home_url: 'https://news.ycombinator.com',
    priority: 8,
  },
  {
    slug: 'github-trending',
    name: 'GitHub Trending (AI)',
    type: 'scraper',
    category: 'community',
    url: 'https://github.com/trending?since=daily&spoken_language_code=',
    home_url: 'https://github.com/trending',
    priority: 7,
  },
  {
    slug: 'huggingface-trending',
    name: 'Hugging Face Trending',
    type: 'api',
    category: 'community',
    url: 'https://huggingface.co/api/trending',
    home_url: 'https://huggingface.co/models?sort=trending',
    priority: 7,
  },

  // ── Person — Blogs (4) ──
  {
    slug: 'karpathy-blog',
    name: 'Andrej Karpathy',
    type: 'rss',
    category: 'person',
    url: 'https://karpathy.github.io/feed.xml',
    home_url: 'https://karpathy.github.io',
    priority: 9,
  },
  {
    slug: 'swyx-blog',
    name: 'swyx (Shawn Wang)',
    type: 'rss',
    category: 'person',
    url: 'https://www.swyx.io/rss.xml',
    home_url: 'https://www.swyx.io/writing',
    priority: 8,
  },
  {
    slug: 'hamel-blog',
    name: 'Hamel Husain',
    type: 'rss',
    category: 'person',
    url: 'https://hamel.dev/feed.xml',
    home_url: 'https://hamel.dev',
    priority: 8,
  },
  // ── Person — Twitter (require TWITTER_BEARER_TOKEN) (3) ──
  {
    slug: 'twitter-sama',
    name: 'Sam Altman',
    type: 'twitter',
    category: 'person',
    url: 'https://api.twitter.com/2/users/by/username/sama/tweets',
    home_url: 'https://twitter.com/sama',
    priority: 10,
    twitter_username: 'sama',
  },
  {
    slug: 'twitter-ylecun',
    name: 'Yann LeCun',
    type: 'twitter',
    category: 'person',
    url: 'https://api.twitter.com/2/users/by/username/ylecun/tweets',
    home_url: 'https://twitter.com/ylecun',
    priority: 9,
    twitter_username: 'ylecun',
  },
  {
    slug: 'twitter-demishassabis',
    name: 'Demis Hassabis',
    type: 'twitter',
    category: 'person',
    url: 'https://api.twitter.com/2/users/by/username/demishassabis/tweets',
    home_url: 'https://twitter.com/demishassabis',
    priority: 9,
    twitter_username: 'demishassabis',
  },

  // ── Person — YouTube RSS (6) ──
  {
    slug: 'yt-karpathy',
    name: 'Andrej Karpathy (YouTube)',
    type: 'rss',
    category: 'person',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCXUPKJO5MZQN11PqgIvyuvQ',
    home_url: 'https://www.youtube.com/@AndrejKarpathy',
    priority: 9,
  },
  {
    slug: 'yt-deepmind',
    name: 'Google DeepMind (YouTube)',
    type: 'rss',
    category: 'person',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCP7jMXSY2xbc3KCAE0MHQ-A',
    home_url: 'https://www.youtube.com/@GoogleDeepMind',
    priority: 8,
  },
  {
    slug: 'yt-anthropic',
    name: 'Anthropic (YouTube)',
    type: 'rss',
    category: 'person',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCBXjHRBbVILc0FeOMBzqLtA',
    home_url: 'https://www.youtube.com/@AnthropicAI',
    priority: 8,
  },
  {
    slug: 'yt-ycombinator',
    name: 'Y Combinator (YouTube)',
    type: 'rss',
    category: 'person',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCcefcZRL2oaA_uBNeo5UOWg',
    home_url: 'https://www.youtube.com/@ycombinator',
    priority: 7,
  },
  {
    slug: 'yt-nopriors',
    name: 'No Priors Podcast (YouTube)',
    type: 'rss',
    category: 'person',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCkMGEz2gMOq0DFTL0JHYmvQ',
    home_url: 'https://www.youtube.com/@NoPriorsPodcast',
    priority: 7,
  },
  {
    slug: 'yt-southparkcommons',
    name: 'South Park Commons (YouTube)',
    type: 'rss',
    category: 'person',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCgPxR0M-aN3bJMGqgLXlS0g',
    home_url: 'https://www.youtube.com/@SouthParkCommons',
    priority: 6,
  },
  {
    slug: 'yt-lennys-podcast',
    name: "Lenny's Podcast (YouTube)",
    type: 'rss',
    category: 'person',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC6t1O76G0jYXOAoYCm153dA',
    home_url: 'https://www.youtube.com/@LennysPodcast',
    priority: 7,
  },
  {
    slug: 'yt-peteryang',
    name: 'Peter Yang (YouTube)',
    type: 'rss',
    category: 'person',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCmINSD_-7jm6yF7aapiyz4A',
    home_url: 'https://www.youtube.com/@peterhyang',
    priority: 7,
  },
  {
    slug: 'yt-unsupervised',
    name: 'Unsupervised Learning (YouTube)',
    type: 'rss',
    category: 'person',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCE6h4Tz0RP34akUoXd_MwzQ',
    home_url: 'https://www.youtube.com/@UnsupervisedLearning',
    priority: 6,
  },

  // ── Newsletter RSS (5) ──
  {
    slug: 'bens-bites',
    name: "Ben's Bites",
    type: 'rss',
    category: 'media',
    url: 'https://bensbites.beehiiv.com/feed',
    home_url: 'https://bensbites.beehiiv.com',
    priority: 8,
  },
  {
    slug: 'ainews-smol',
    name: 'AI News (smol.ai)',
    type: 'rss',
    category: 'media',
    url: 'https://buttondown.com/ainews/rss',
    home_url: 'https://buttondown.com/ainews',
    priority: 7,
  },
  {
    slug: 'a16z-blog',
    name: 'a16z Blog',
    type: 'rss',
    category: 'media',
    url: 'https://a16z.com/feed/',
    home_url: 'https://a16z.com',
    priority: 7,
  },
  {
    slug: 'deeplearning-ai',
    name: 'deeplearning.ai (The Batch)',
    type: 'rss',
    category: 'media',
    url: 'https://www.deeplearning.ai/the-batch/feed/',
    home_url: 'https://www.deeplearning.ai/the-batch',
    priority: 8,
  },

  // ── Media (5) ──
  {
    slug: 'techcrunch-ai',
    name: 'TechCrunch AI',
    type: 'rss',
    category: 'media',
    url: 'https://techcrunch.com/category/artificial-intelligence/feed/',
    home_url: 'https://techcrunch.com/category/artificial-intelligence',
    priority: 7,
  },
  {
    slug: 'cnbc-tech',
    name: 'CNBC Technology',
    type: 'rss',
    category: 'media',
    url: 'https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=19854910',
    home_url: 'https://www.cnbc.com/technology',
    priority: 6,
  },
  {
    slug: 'producthunt',
    name: 'Product Hunt',
    type: 'rss',
    category: 'media',
    url: 'https://www.producthunt.com/feed',
    home_url: 'https://www.producthunt.com',
    priority: 6,
  },

  // ── OPML Blog Feeds (92) ──
  {
    slug: 'blog-simonwillison-net',
    name: 'simonwillison.net',
    type: 'rss',
    category: 'person',
    url: 'https://simonwillison.net/atom/everything/',
    home_url: 'https://simonwillison.net',
    priority: 6,
  },
  {
    slug: 'blog-jeffgeerling-com',
    name: 'jeffgeerling.com',
    type: 'rss',
    category: 'person',
    url: 'https://www.jeffgeerling.com/blog.xml',
    home_url: 'https://jeffgeerling.com',
    priority: 6,
  },
  {
    slug: 'blog-seangoedecke-com',
    name: 'seangoedecke.com',
    type: 'rss',
    category: 'person',
    url: 'https://www.seangoedecke.com/rss.xml',
    home_url: 'https://seangoedecke.com',
    priority: 6,
  },
  {
    slug: 'blog-krebsonsecurity-com',
    name: 'krebsonsecurity.com',
    type: 'rss',
    category: 'person',
    url: 'https://krebsonsecurity.com/feed/',
    home_url: 'https://krebsonsecurity.com',
    priority: 6,
  },
  {
    slug: 'blog-daringfireball-net',
    name: 'daringfireball.net',
    type: 'rss',
    category: 'person',
    url: 'https://daringfireball.net/feeds/main',
    home_url: 'https://daringfireball.net',
    priority: 6,
  },
  {
    slug: 'blog-ericmigi-com',
    name: 'ericmigi.com',
    type: 'rss',
    category: 'person',
    url: 'https://ericmigi.com/rss.xml',
    home_url: 'https://ericmigi.com',
    priority: 6,
  },
  {
    slug: 'blog-antirez-com',
    name: 'antirez.com',
    type: 'rss',
    category: 'person',
    url: 'http://antirez.com/rss',
    home_url: 'http://antirez.com',
    priority: 6,
  },
  {
    slug: 'blog-idiallo-com',
    name: 'idiallo.com',
    type: 'rss',
    category: 'person',
    url: 'https://idiallo.com/feed.rss',
    home_url: 'https://idiallo.com',
    priority: 6,
  },
  {
    slug: 'blog-maurycyz-com',
    name: 'maurycyz.com',
    type: 'rss',
    category: 'person',
    url: 'https://maurycyz.com/index.xml',
    home_url: 'https://maurycyz.com',
    priority: 6,
  },
  {
    slug: 'blog-pluralistic-net',
    name: 'pluralistic.net',
    type: 'rss',
    category: 'person',
    url: 'https://pluralistic.net/feed/',
    home_url: 'https://pluralistic.net',
    priority: 6,
  },
  {
    slug: 'blog-shkspr-mobi',
    name: 'shkspr.mobi',
    type: 'rss',
    category: 'person',
    url: 'https://shkspr.mobi/blog/feed/',
    home_url: 'https://shkspr.mobi',
    priority: 6,
  },
  {
    slug: 'blog-lcamtuf-substack-com',
    name: 'lcamtuf.substack.com',
    type: 'rss',
    category: 'person',
    url: 'https://lcamtuf.substack.com/feed',
    home_url: 'https://lcamtuf.substack.com',
    priority: 6,
  },
  {
    slug: 'blog-mitchellh-com',
    name: 'mitchellh.com',
    type: 'rss',
    category: 'person',
    url: 'https://mitchellh.com/feed.xml',
    home_url: 'https://mitchellh.com',
    priority: 6,
  },
  {
    slug: 'blog-dynomight-net',
    name: 'dynomight.net',
    type: 'rss',
    category: 'person',
    url: 'https://dynomight.net/feed.xml',
    home_url: 'https://dynomight.net',
    priority: 6,
  },
  {
    slug: 'blog-utcc-utoronto-ca-cks',
    name: 'utcc.utoronto.ca/~cks',
    type: 'rss',
    category: 'person',
    url: 'https://utcc.utoronto.ca/~cks/space/blog/?atom',
    home_url: 'https://utcc.utoronto.ca/~cks',
    priority: 6,
  },
  {
    slug: 'blog-xeiaso-net',
    name: 'xeiaso.net',
    type: 'rss',
    category: 'person',
    url: 'https://xeiaso.net/blog.rss',
    home_url: 'https://xeiaso.net',
    priority: 6,
  },
  {
    slug: 'blog-devblogs-microsoft-com-oldnewthing',
    name: 'devblogs.microsoft.com/oldnewthing',
    type: 'rss',
    category: 'person',
    url: 'https://devblogs.microsoft.com/oldnewthing/feed',
    home_url: 'https://devblogs.microsoft.com/oldnewthing',
    priority: 6,
  },
  {
    slug: 'blog-righto-com',
    name: 'righto.com',
    type: 'rss',
    category: 'person',
    url: 'https://www.righto.com/feeds/posts/default',
    home_url: 'https://righto.com',
    priority: 6,
  },
  {
    slug: 'blog-lucumr-pocoo-org',
    name: 'lucumr.pocoo.org',
    type: 'rss',
    category: 'person',
    url: 'https://lucumr.pocoo.org/feed.atom',
    home_url: 'https://lucumr.pocoo.org',
    priority: 6,
  },
  {
    slug: 'blog-skyfall-dev',
    name: 'skyfall.dev',
    type: 'rss',
    category: 'person',
    url: 'https://skyfall.dev/rss.xml',
    home_url: 'https://skyfall.dev',
    priority: 6,
  },
  {
    slug: 'blog-garymarcus-substack-com',
    name: 'garymarcus.substack.com',
    type: 'rss',
    category: 'person',
    url: 'https://garymarcus.substack.com/feed',
    home_url: 'https://garymarcus.substack.com',
    priority: 6,
  },
  {
    slug: 'blog-rachelbythebay-com',
    name: 'rachelbythebay.com',
    type: 'rss',
    category: 'person',
    url: 'https://rachelbythebay.com/w/atom.xml',
    home_url: 'https://rachelbythebay.com',
    priority: 6,
  },
  {
    slug: 'blog-overreacted-io',
    name: 'overreacted.io',
    type: 'rss',
    category: 'person',
    url: 'https://overreacted.io/rss.xml',
    home_url: 'https://overreacted.io',
    priority: 6,
  },
  {
    slug: 'blog-timsh-org',
    name: 'timsh.org',
    type: 'rss',
    category: 'person',
    url: 'https://timsh.org/rss/',
    home_url: 'https://timsh.org',
    priority: 6,
  },
  {
    slug: 'blog-johndcook-com',
    name: 'johndcook.com',
    type: 'rss',
    category: 'person',
    url: 'https://www.johndcook.com/blog/feed/',
    home_url: 'https://johndcook.com',
    priority: 6,
  },
  {
    slug: 'blog-gilesthomas-com',
    name: 'gilesthomas.com',
    type: 'rss',
    category: 'person',
    url: 'https://gilesthomas.com/feed/rss.xml',
    home_url: 'https://gilesthomas.com',
    priority: 6,
  },
  {
    slug: 'blog-matklad-github-io',
    name: 'matklad.github.io',
    type: 'rss',
    category: 'person',
    url: 'https://matklad.github.io/feed.xml',
    home_url: 'https://matklad.github.io',
    priority: 6,
  },
  {
    slug: 'blog-derekthompson-org',
    name: 'derekthompson.org',
    type: 'rss',
    category: 'person',
    url: 'https://www.theatlantic.com/feed/author/derek-thompson/',
    home_url: 'https://derekthompson.org',
    priority: 6,
  },
  {
    slug: 'blog-evanhahn-com',
    name: 'evanhahn.com',
    type: 'rss',
    category: 'person',
    url: 'https://evanhahn.com/feed.xml',
    home_url: 'https://evanhahn.com',
    priority: 6,
  },
  {
    slug: 'blog-terriblesoftware-org',
    name: 'terriblesoftware.org',
    type: 'rss',
    category: 'person',
    url: 'https://terriblesoftware.org/feed/',
    home_url: 'https://terriblesoftware.org',
    priority: 6,
  },
  {
    slug: 'blog-rakhim-exotext-com',
    name: 'rakhim.exotext.com',
    type: 'rss',
    category: 'person',
    url: 'https://rakhim.exotext.com/rss.xml',
    home_url: 'https://rakhim.exotext.com',
    priority: 6,
  },
  {
    slug: 'blog-joanwestenberg-com',
    name: 'joanwestenberg.com',
    type: 'rss',
    category: 'person',
    url: 'https://joanwestenberg.com/rss',
    home_url: 'https://joanwestenberg.com',
    priority: 6,
  },
  {
    slug: 'blog-xania-org',
    name: 'xania.org',
    type: 'rss',
    category: 'person',
    url: 'https://xania.org/feed',
    home_url: 'https://xania.org',
    priority: 6,
  },
  {
    slug: 'blog-micahflee-com',
    name: 'micahflee.com',
    type: 'rss',
    category: 'person',
    url: 'https://micahflee.com/feed/',
    home_url: 'https://micahflee.com',
    priority: 6,
  },
  {
    slug: 'blog-nesbitt-io',
    name: 'nesbitt.io',
    type: 'rss',
    category: 'person',
    url: 'https://nesbitt.io/feed.xml',
    home_url: 'https://nesbitt.io',
    priority: 6,
  },
  {
    slug: 'blog-construction-physics-com',
    name: 'construction-physics.com',
    type: 'rss',
    category: 'person',
    url: 'https://www.construction-physics.com/feed',
    home_url: 'https://construction-physics.com',
    priority: 6,
  },
  {
    slug: 'blog-tedium-co',
    name: 'tedium.co',
    type: 'rss',
    category: 'person',
    url: 'https://feed.tedium.co/',
    home_url: 'https://tedium.co',
    priority: 6,
  },
  {
    slug: 'blog-susam-net',
    name: 'susam.net',
    type: 'rss',
    category: 'person',
    url: 'https://susam.net/feed.xml',
    home_url: 'https://susam.net',
    priority: 6,
  },
  {
    slug: 'blog-entropicthoughts-com',
    name: 'entropicthoughts.com',
    type: 'rss',
    category: 'person',
    url: 'https://entropicthoughts.com/feed.xml',
    home_url: 'https://entropicthoughts.com',
    priority: 6,
  },
  {
    slug: 'blog-buttondown-com-hillelwayne',
    name: 'buttondown.com/hillelwayne',
    type: 'rss',
    category: 'person',
    url: 'https://buttondown.com/hillelwayne/rss',
    home_url: 'https://buttondown.com/hillelwayne',
    priority: 6,
  },
  {
    slug: 'blog-dwarkesh-com',
    name: 'dwarkesh.com',
    type: 'rss',
    category: 'person',
    url: 'https://www.dwarkeshpatel.com/feed',
    home_url: 'https://dwarkesh.com',
    priority: 6,
  },
  {
    slug: 'blog-borretti-me',
    name: 'borretti.me',
    type: 'rss',
    category: 'person',
    url: 'https://borretti.me/feed.xml',
    home_url: 'https://borretti.me',
    priority: 6,
  },
  {
    slug: 'blog-wheresyoured-at',
    name: 'wheresyoured.at',
    type: 'rss',
    category: 'person',
    url: 'https://www.wheresyoured.at/rss/',
    home_url: 'https://wheresyoured.at',
    priority: 6,
  },
  {
    slug: 'blog-jayd-ml',
    name: 'jayd.ml',
    type: 'rss',
    category: 'person',
    url: 'https://jayd.ml/feed.xml',
    home_url: 'https://jayd.ml',
    priority: 6,
  },
  {
    slug: 'blog-minimaxir-com',
    name: 'minimaxir.com',
    type: 'rss',
    category: 'person',
    url: 'https://minimaxir.com/index.xml',
    home_url: 'https://minimaxir.com',
    priority: 6,
  },
  {
    slug: 'blog-geohot-github-io',
    name: 'geohot.github.io',
    type: 'rss',
    category: 'person',
    url: 'https://geohot.github.io/blog/feed.xml',
    home_url: 'https://geohot.github.io',
    priority: 6,
  },
  {
    slug: 'blog-paulgraham-com',
    name: 'paulgraham.com',
    type: 'rss',
    category: 'person',
    url: 'http://www.aaronsw.com/2002/feeds/pgessays.rss',
    home_url: 'https://paulgraham.com',
    priority: 6,
  },
  {
    slug: 'blog-filfre-net',
    name: 'filfre.net',
    type: 'rss',
    category: 'person',
    url: 'https://www.filfre.net/feed/',
    home_url: 'https://filfre.net',
    priority: 6,
  },
  {
    slug: 'blog-blog-jim-nielsen-com',
    name: 'blog.jim-nielsen.com',
    type: 'rss',
    category: 'person',
    url: 'https://blog.jim-nielsen.com/feed.xml',
    home_url: 'https://blog.jim-nielsen.com',
    priority: 6,
  },
  {
    slug: 'blog-dfarq-homeip-net',
    name: 'dfarq.homeip.net',
    type: 'rss',
    category: 'person',
    url: 'https://dfarq.homeip.net/feed/',
    home_url: 'https://dfarq.homeip.net',
    priority: 6,
  },
  {
    slug: 'blog-jyn-dev',
    name: 'jyn.dev',
    type: 'rss',
    category: 'person',
    url: 'https://jyn.dev/atom.xml',
    home_url: 'https://jyn.dev',
    priority: 6,
  },
  {
    slug: 'blog-geoffreylitt-com',
    name: 'geoffreylitt.com',
    type: 'rss',
    category: 'person',
    url: 'https://www.geoffreylitt.com/feed.xml',
    home_url: 'https://geoffreylitt.com',
    priority: 6,
  },
  {
    slug: 'blog-downtowndougbrown-com',
    name: 'downtowndougbrown.com',
    type: 'rss',
    category: 'person',
    url: 'https://www.downtowndougbrown.com/feed/',
    home_url: 'https://downtowndougbrown.com',
    priority: 6,
  },
  {
    slug: 'blog-brutecat-com',
    name: 'brutecat.com',
    type: 'rss',
    category: 'person',
    url: 'https://brutecat.com/rss.xml',
    home_url: 'https://brutecat.com',
    priority: 6,
  },
  {
    slug: 'blog-eli-thegreenplace-net',
    name: 'eli.thegreenplace.net',
    type: 'rss',
    category: 'person',
    url: 'https://eli.thegreenplace.net/feeds/all.atom.xml',
    home_url: 'https://eli.thegreenplace.net',
    priority: 6,
  },
  {
    slug: 'blog-abortretry-fail',
    name: 'abortretry.fail',
    type: 'rss',
    category: 'person',
    url: 'https://www.abortretry.fail/feed',
    home_url: 'https://abortretry.fail',
    priority: 6,
  },
  {
    slug: 'blog-fabiensanglard-net',
    name: 'fabiensanglard.net',
    type: 'rss',
    category: 'person',
    url: 'https://fabiensanglard.net/rss.xml',
    home_url: 'https://fabiensanglard.net',
    priority: 6,
  },
  {
    slug: 'blog-oldvcr-blogspot-com',
    name: 'oldvcr.blogspot.com',
    type: 'rss',
    category: 'person',
    url: 'https://oldvcr.blogspot.com/feeds/posts/default',
    home_url: 'https://oldvcr.blogspot.com',
    priority: 6,
  },
  {
    slug: 'blog-bogdanthegeek-github-io',
    name: 'bogdanthegeek.github.io',
    type: 'rss',
    category: 'person',
    url: 'https://bogdanthegeek.github.io/blog/index.xml',
    home_url: 'https://bogdanthegeek.github.io',
    priority: 6,
  },
  {
    slug: 'blog-hugotunius-se',
    name: 'hugotunius.se',
    type: 'rss',
    category: 'person',
    url: 'https://hugotunius.se/feed.xml',
    home_url: 'https://hugotunius.se',
    priority: 6,
  },
  {
    slug: 'blog-gwern-net',
    name: 'gwern.net',
    type: 'rss',
    category: 'person',
    url: 'https://gwern.substack.com/feed',
    home_url: 'https://gwern.net',
    priority: 6,
  },
  {
    slug: 'blog-berthub-eu',
    name: 'berthub.eu',
    type: 'rss',
    category: 'person',
    url: 'https://berthub.eu/articles/index.xml',
    home_url: 'https://berthub.eu',
    priority: 6,
  },
  {
    slug: 'blog-chadnauseam-com',
    name: 'chadnauseam.com',
    type: 'rss',
    category: 'person',
    url: 'https://chadnauseam.com/rss.xml',
    home_url: 'https://chadnauseam.com',
    priority: 6,
  },
  {
    slug: 'blog-simone-org',
    name: 'simone.org',
    type: 'rss',
    category: 'person',
    url: 'https://simone.org/feed/',
    home_url: 'https://simone.org',
    priority: 6,
  },
  {
    slug: 'blog-it-notes-dragas-net',
    name: 'it-notes.dragas.net',
    type: 'rss',
    category: 'person',
    url: 'https://it-notes.dragas.net/feed/',
    home_url: 'https://it-notes.dragas.net',
    priority: 6,
  },
  {
    slug: 'blog-beej-us',
    name: 'beej.us',
    type: 'rss',
    category: 'person',
    url: 'https://beej.us/blog/rss.xml',
    home_url: 'https://beej.us',
    priority: 6,
  },
  {
    slug: 'blog-hey-paris',
    name: 'hey.paris',
    type: 'rss',
    category: 'person',
    url: 'https://hey.paris/index.xml',
    home_url: 'https://hey.paris',
    priority: 6,
  },
  {
    slug: 'blog-danielwirtz-com',
    name: 'danielwirtz.com',
    type: 'rss',
    category: 'person',
    url: 'https://danielwirtz.com/rss.xml',
    home_url: 'https://danielwirtz.com',
    priority: 6,
  },
  {
    slug: 'blog-matduggan-com',
    name: 'matduggan.com',
    type: 'rss',
    category: 'person',
    url: 'https://matduggan.com/rss/',
    home_url: 'https://matduggan.com',
    priority: 6,
  },
  {
    slug: 'blog-refactoringenglish-com',
    name: 'refactoringenglish.com',
    type: 'rss',
    category: 'person',
    url: 'https://refactoringenglish.com/index.xml',
    home_url: 'https://refactoringenglish.com',
    priority: 6,
  },
  {
    slug: 'blog-worksonmymachine-substack-com',
    name: 'worksonmymachine.substack.com',
    type: 'rss',
    category: 'person',
    url: 'https://worksonmymachine.substack.com/feed',
    home_url: 'https://worksonmymachine.substack.com',
    priority: 6,
  },
  {
    slug: 'blog-philiplaine-com',
    name: 'philiplaine.com',
    type: 'rss',
    category: 'person',
    url: 'https://philiplaine.com/index.xml',
    home_url: 'https://philiplaine.com',
    priority: 6,
  },
  {
    slug: 'blog-steveblank-com',
    name: 'steveblank.com',
    type: 'rss',
    category: 'person',
    url: 'https://steveblank.com/feed/',
    home_url: 'https://steveblank.com',
    priority: 6,
  },
  {
    slug: 'blog-bernsteinbear-com',
    name: 'bernsteinbear.com',
    type: 'rss',
    category: 'person',
    url: 'https://bernsteinbear.com/feed.xml',
    home_url: 'https://bernsteinbear.com',
    priority: 6,
  },
  {
    slug: 'blog-danieldelaney-net',
    name: 'danieldelaney.net',
    type: 'rss',
    category: 'person',
    url: 'https://danieldelaney.net/feed',
    home_url: 'https://danieldelaney.net',
    priority: 6,
  },
  {
    slug: 'blog-troyhunt-com',
    name: 'troyhunt.com',
    type: 'rss',
    category: 'person',
    url: 'https://www.troyhunt.com/rss/',
    home_url: 'https://troyhunt.com',
    priority: 6,
  },
  {
    slug: 'blog-herman-bearblog-dev',
    name: 'herman.bearblog.dev',
    type: 'rss',
    category: 'person',
    url: 'https://herman.bearblog.dev/feed/',
    home_url: 'https://herman.bearblog.dev',
    priority: 6,
  },
  {
    slug: 'blog-tomrenner-com',
    name: 'tomrenner.com',
    type: 'rss',
    category: 'person',
    url: 'https://tomrenner.com/index.xml',
    home_url: 'https://tomrenner.com',
    priority: 6,
  },
  {
    slug: 'blog-blog-pixelmelt-dev',
    name: 'blog.pixelmelt.dev',
    type: 'rss',
    category: 'person',
    url: 'https://blog.pixelmelt.dev/rss/',
    home_url: 'https://blog.pixelmelt.dev',
    priority: 6,
  },
  {
    slug: 'blog-martinalderson-com',
    name: 'martinalderson.com',
    type: 'rss',
    category: 'person',
    url: 'https://martinalderson.com/feed.xml',
    home_url: 'https://martinalderson.com',
    priority: 6,
  },
  {
    slug: 'blog-danielchasehooper-com',
    name: 'danielchasehooper.com',
    type: 'rss',
    category: 'person',
    url: 'https://danielchasehooper.com/feed.xml',
    home_url: 'https://danielchasehooper.com',
    priority: 6,
  },
  {
    slug: 'blog-chiark-greenend-org-uk-sgtatham',
    name: 'chiark.greenend.org.uk/~sgtatham',
    type: 'rss',
    category: 'person',
    url: 'https://www.chiark.greenend.org.uk/~sgtatham/quasiblog/feed.xml',
    home_url: 'https://chiark.greenend.org.uk/~sgtatham',
    priority: 6,
  },
  {
    slug: 'blog-grantslatton-com',
    name: 'grantslatton.com',
    type: 'rss',
    category: 'person',
    url: 'https://grantslatton.com/rss.xml',
    home_url: 'https://grantslatton.com',
    priority: 6,
  },
  {
    slug: 'blog-experimental-history-com',
    name: 'experimental-history.com',
    type: 'rss',
    category: 'person',
    url: 'https://www.experimental-history.com/feed',
    home_url: 'https://experimental-history.com',
    priority: 6,
  },
  {
    slug: 'blog-anildash-com',
    name: 'anildash.com',
    type: 'rss',
    category: 'person',
    url: 'https://anildash.com/feed.xml',
    home_url: 'https://anildash.com',
    priority: 6,
  },
  {
    slug: 'blog-aresluna-org',
    name: 'aresluna.org',
    type: 'rss',
    category: 'person',
    url: 'https://aresluna.org/main.rss',
    home_url: 'https://aresluna.org',
    priority: 6,
  },
  {
    slug: 'blog-michael-stapelberg-ch',
    name: 'michael.stapelberg.ch',
    type: 'rss',
    category: 'person',
    url: 'https://michael.stapelberg.ch/feed.xml',
    home_url: 'https://michael.stapelberg.ch',
    priority: 6,
  },
  {
    slug: 'blog-miguelgrinberg-com',
    name: 'miguelgrinberg.com',
    type: 'rss',
    category: 'person',
    url: 'https://blog.miguelgrinberg.com/feed',
    home_url: 'https://miguelgrinberg.com',
    priority: 6,
  },
  {
    slug: 'blog-keygen-sh',
    name: 'keygen.sh',
    type: 'rss',
    category: 'person',
    url: 'https://keygen.sh/blog/feed.xml',
    home_url: 'https://keygen.sh',
    priority: 6,
  },
  {
    slug: 'blog-mjg59-dreamwidth-org',
    name: 'mjg59.dreamwidth.org',
    type: 'rss',
    category: 'person',
    url: 'https://mjg59.dreamwidth.org/data/rss',
    home_url: 'https://mjg59.dreamwidth.org',
    priority: 6,
  },
  {
    slug: 'blog-computer-rip',
    name: 'computer.rip',
    type: 'rss',
    category: 'person',
    url: 'https://computer.rip/rss.xml',
    home_url: 'https://computer.rip',
    priority: 6,
  },
  {
    slug: 'blog-tedunangst-com',
    name: 'tedunangst.com',
    type: 'rss',
    category: 'person',
    url: 'https://www.tedunangst.com/flak/rss',
    home_url: 'https://tedunangst.com',
    priority: 6,
  },
]

// Sources that don't need Twitter API
export const NON_TWITTER_SOURCES = SOURCE_CONFIGS.filter(s => s.type !== 'twitter')

// Sources that need Twitter API
export const TWITTER_SOURCES = SOURCE_CONFIGS.filter(s => s.type === 'twitter')
