import type { SourceConfig } from '../types'

// ======================================================
// AI Radar - 全部信源配置 (~38 sources)
// ======================================================

export const SOURCE_CONFIGS: SourceConfig[] = [
  // ── Official (9) ──
  {
    slug: 'openai-blog',
    name: 'OpenAI Blog',
    type: 'rss',
    category: 'official',
    url: 'https://openai.com/blog/rss.xml',
    home_url: 'https://openai.com/blog',
    priority: 10,
  },
  {
    slug: 'anthropic-blog',
    name: 'Anthropic Blog',
    type: 'rss',
    category: 'official',
    url: 'https://www.anthropic.com/rss.xml',
    home_url: 'https://www.anthropic.com/news',
    priority: 10,
  },
  {
    slug: 'deepmind-blog',
    name: 'Google DeepMind Blog',
    type: 'rss',
    category: 'official',
    url: 'https://deepmind.google/blog/rss.xml',
    home_url: 'https://deepmind.google/blog',
    priority: 9,
  },
  {
    slug: 'google-ai-blog',
    name: 'Google AI Blog',
    type: 'rss',
    category: 'official',
    url: 'https://blog.google/technology/ai/rss/',
    home_url: 'https://blog.google/technology/ai',
    priority: 9,
  },
  {
    slug: 'meta-ai-blog',
    name: 'Meta AI Blog',
    type: 'rss',
    category: 'official',
    url: 'https://ai.meta.com/blog/rss/',
    home_url: 'https://ai.meta.com/blog',
    priority: 9,
  },
  {
    slug: 'nvidia-ai-blog',
    name: 'NVIDIA AI Blog',
    type: 'rss',
    category: 'official',
    url: 'https://blogs.nvidia.com/feed/',
    home_url: 'https://blogs.nvidia.com/blog/category/generative-ai',
    priority: 8,
  },
  {
    slug: 'huggingface-blog',
    name: 'Hugging Face Blog',
    type: 'rss',
    category: 'official',
    url: 'https://huggingface.co/blog/feed.xml',
    home_url: 'https://huggingface.co/blog',
    priority: 9,
  },
  {
    slug: 'xai-blog',
    name: 'xAI Blog',
    type: 'rss',
    category: 'official',
    url: 'https://x.ai/blog/rss.xml',
    home_url: 'https://x.ai/blog',
    priority: 9,
  },
  {
    slug: 'google-gemini-blog',
    name: 'Google Gemini Blog',
    type: 'rss',
    category: 'official',
    url: 'https://blog.google/products/gemini/rss/',
    home_url: 'https://blog.google/products/gemini',
    priority: 9,
  },
  {
    slug: 'azure-ai-blog',
    name: 'Azure AI Blog',
    type: 'rss',
    category: 'official',
    url: 'https://azure.microsoft.com/en-us/blog/tag/ai/feed/',
    home_url: 'https://azure.microsoft.com/en-us/blog/tag/ai',
    priority: 8,
  },

  // ── 国内媒体 (2) ──
  {
    slug: '36kr',
    name: '36氪',
    type: 'rss',
    category: 'media',
    url: 'https://36kr.com/feed',
    home_url: 'https://36kr.com',
    priority: 7,
  },
  {
    slug: 'qbitai',
    name: '量子位',
    type: 'rss',
    category: 'media',
    url: 'https://www.qbitai.com/feed',
    home_url: 'https://www.qbitai.com',
    priority: 7,
  },

  // ── Community (4) ──
  {
    slug: 'hackernews',
    name: 'Hacker News',
    type: 'api',
    category: 'community',
    url: 'https://hacker-news.firebaseio.com/v0',
    home_url: 'https://news.ycombinator.com',
    priority: 8,
  },
  {
    slug: 'github-trending',
    name: 'GitHub Trending (AI)',
    type: 'scraper',
    category: 'community',
    url: 'https://github.com/trending?since=daily&spoken_language_code=',
    home_url: 'https://github.com/trending',
    priority: 7,
  },
  {
    slug: 'huggingface-trending',
    name: 'Hugging Face Trending',
    type: 'api',
    category: 'community',
    url: 'https://huggingface.co/api/trending',
    home_url: 'https://huggingface.co/models?sort=trending',
    priority: 7,
  },

  // ── Person — Blogs (4) ──
  {
    slug: 'karpathy-blog',
    name: 'Andrej Karpathy',
    type: 'rss',
    category: 'person',
    url: 'https://karpathy.github.io/feed.xml',
    home_url: 'https://karpathy.github.io',
    priority: 9,
  },
  {
    slug: 'swyx-blog',
    name: 'swyx (Shawn Wang)',
    type: 'rss',
    category: 'person',
    url: 'https://www.swyx.io/rss.xml',
    home_url: 'https://www.swyx.io/writing',
    priority: 8,
  },
  {
    slug: 'hamel-blog',
    name: 'Hamel Husain',
    type: 'rss',
    category: 'person',
    url: 'https://hamel.dev/feed.xml',
    home_url: 'https://hamel.dev',
    priority: 8,
  },
  // ── Person — Twitter (require TWITTER_BEARER_TOKEN) (3) ──
  {
    slug: 'twitter-sama',
    name: 'Sam Altman',
    type: 'twitter',
    category: 'person',
    url: 'https://api.twitter.com/2/users/by/username/sama/tweets',
    home_url: 'https://twitter.com/sama',
    priority: 10,
    twitter_username: 'sama',
  },
  {
    slug: 'twitter-ylecun',
    name: 'Yann LeCun',
    type: 'twitter',
    category: 'person',
    url: 'https://api.twitter.com/2/users/by/username/ylecun/tweets',
    home_url: 'https://twitter.com/ylecun',
    priority: 9,
    twitter_username: 'ylecun',
  },
  {
    slug: 'twitter-demishassabis',
    name: 'Demis Hassabis',
    type: 'twitter',
    category: 'person',
    url: 'https://api.twitter.com/2/users/by/username/demishassabis/tweets',
    home_url: 'https://twitter.com/demishassabis',
    priority: 9,
    twitter_username: 'demishassabis',
  },

  // ── Person — YouTube RSS (6) ──
  {
    slug: 'yt-karpathy',
    name: 'Andrej Karpathy (YouTube)',
    type: 'rss',
    category: 'person',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCXUPKJO5MZQN11PqgIvyuvQ',
    home_url: 'https://www.youtube.com/@AndrejKarpathy',
    priority: 9,
  },
  {
    slug: 'yt-deepmind',
    name: 'Google DeepMind (YouTube)',
    type: 'rss',
    category: 'person',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCP7jMXSY2xbc3KCAE0MHQ-A',
    home_url: 'https://www.youtube.com/@GoogleDeepMind',
    priority: 8,
  },
  {
    slug: 'yt-anthropic',
    name: 'Anthropic (YouTube)',
    type: 'rss',
    category: 'person',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCBXjHRBbVILc0FeOMBzqLtA',
    home_url: 'https://www.youtube.com/@AnthropicAI',
    priority: 8,
  },
  {
    slug: 'yt-ycombinator',
    name: 'Y Combinator (YouTube)',
    type: 'rss',
    category: 'person',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCcefcZRL2oaA_uBNeo5UOWg',
    home_url: 'https://www.youtube.com/@ycombinator',
    priority: 7,
  },
  {
    slug: 'yt-nopriors',
    name: 'No Priors Podcast (YouTube)',
    type: 'rss',
    category: 'person',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCkMGEz2gMOq0DFTL0JHYmvQ',
    home_url: 'https://www.youtube.com/@NoPriorsPodcast',
    priority: 7,
  },
  {
    slug: 'yt-southparkcommons',
    name: 'South Park Commons (YouTube)',
    type: 'rss',
    category: 'person',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCgPxR0M-aN3bJMGqgLXlS0g',
    home_url: 'https://www.youtube.com/@SouthParkCommons',
    priority: 6,
  },
  {
    slug: 'yt-lennys-podcast',
    name: "Lenny's Podcast (YouTube)",
    type: 'rss',
    category: 'person',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC6t1O76G0jYXOAoYCm153dA',
    home_url: 'https://www.youtube.com/@LennysPodcast',
    priority: 7,
  },
  {
    slug: 'yt-peteryang',
    name: 'Peter Yang (YouTube)',
    type: 'rss',
    category: 'person',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCmINSD_-7jm6yF7aapiyz4A',
    home_url: 'https://www.youtube.com/@peterhyang',
    priority: 7,
  },
  {
    slug: 'yt-unsupervised',
    name: 'Unsupervised Learning (YouTube)',
    type: 'rss',
    category: 'person',
    url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCE6h4Tz0RP34akUoXd_MwzQ',
    home_url: 'https://www.youtube.com/@UnsupervisedLearning',
    priority: 6,
  },

  // ── Newsletter RSS (5) ──
  {
    slug: 'bens-bites',
    name: "Ben's Bites",
    type: 'rss',
    category: 'media',
    url: 'https://bensbites.beehiiv.com/feed',
    home_url: 'https://bensbites.beehiiv.com',
    priority: 8,
  },
  {
    slug: 'ainews-smol',
    name: 'AI News (smol.ai)',
    type: 'rss',
    category: 'media',
    url: 'https://buttondown.com/ainews/rss',
    home_url: 'https://buttondown.com/ainews',
    priority: 7,
  },
  {
    slug: 'a16z-blog',
    name: 'a16z Blog',
    type: 'rss',
    category: 'media',
    url: 'https://a16z.com/feed/',
    home_url: 'https://a16z.com',
    priority: 7,
  },
  {
    slug: 'deeplearning-ai',
    name: 'deeplearning.ai (The Batch)',
    type: 'rss',
    category: 'media',
    url: 'https://www.deeplearning.ai/the-batch/feed/',
    home_url: 'https://www.deeplearning.ai/the-batch',
    priority: 8,
  },

  // ── Media (5) ──
  {
    slug: 'techcrunch-ai',
    name: 'TechCrunch AI',
    type: 'rss',
    category: 'media',
    url: 'https://techcrunch.com/category/artificial-intelligence/feed/',
    home_url: 'https://techcrunch.com/category/artificial-intelligence',
    priority: 7,
  },
  {
    slug: 'cnbc-tech',
    name: 'CNBC Technology',
    type: 'rss',
    category: 'media',
    url: 'https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=19854910',
    home_url: 'https://www.cnbc.com/technology',
    priority: 6,
  },
  {
    slug: 'producthunt',
    name: 'Product Hunt',
    type: 'rss',
    category: 'media',
    url: 'https://www.producthunt.com/feed',
    home_url: 'https://www.producthunt.com',
    priority: 6,
  },
]

// Sources that don't need Twitter API
export const NON_TWITTER_SOURCES = SOURCE_CONFIGS.filter(s => s.type !== 'twitter')

// Sources that need Twitter API
export const TWITTER_SOURCES = SOURCE_CONFIGS.filter(s => s.type === 'twitter')
